apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: mongopv
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mongo-pv2
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: default
  name: mongopv
spec:
  storageClassName: standard
  volumeName: mongopv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
