apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    run: node-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      run: node
  template:
    metadata:
      labels:
        run: node
    spec:
      containers:
      - name: node-app
        image: jobri237/lab4-app:1
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: db-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    run: mongo-depl
spec:
  selector:
    matchLabels:
      run: mongodb
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
      - name: mongodb-app
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MONGO_INITDB_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MONGO_INITDB_ROOT_PASSWORD
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
      volumes:
       - name: mongo-data
         hostPath:
           path: /data
           type: DirectoryOrCreate

