apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-share1
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /share1
    server: 10.1.1.28
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-share2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /share2
    server: 10.1.1.28
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-share3
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /share3
    server: 10.1.1.28
