apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    run: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      run: node
  template:
    metadata:
      labels:
        run: node 
    spec:
      containers:
      - name: node-app
        image: jobri237/lab4-app:1

