apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db-sts
spec:
  selector:
    matchLabels:
      run: mongodb 
  serviceName: "mongo-service"
  replicas: 1
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
      - name: mongodb-app
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongo-secret
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
      tolerations:
        - key: "type"
          operator: "Equal"
          value: "db"
          effect: "NoSchedule"
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        storageClassName: default
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 90Mi
