apiVersion: v1
kind: Service
metadata:
  name: db-headless-svc
  labels:
    run: mongodb
spec:
  ports:
  - protocol: TCP
    port: 27017
  clusterIP: None
  selector:
    run: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db-sts
spec:
  selector:
    matchLabels:
      run: mongodb 
  serviceName: "db-headless-svc"
  replicas: 3
  template:
    metadata:
      labels:
        run: mongodb
    spec:
      containers:
      - name: mongodb-app
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: mongo-secret
        volumeMounts:
          - mountPath: /data/db
            name: mongo-data
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 90Mi
