version: '3'
services:
  my-app:
    build: .
    depends_on:
    - "mongodb"
    image: jobri237/lab4-app:${TAG}
    env_file:
      - mongo.env 
    ports:
      - 80:80
  mongodb:
    image: mongo
    ports:
      - ${MONGO_DB_PORT}:${MONGO_DB_PORT}
    env_file:
      - mongo.env
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8080:8081
    env_file:
      - express.env
    depends_on:
     - "mongodb"
volumes:
  mongo-data:
    driver: local
