apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.configmap }}
data:
  MONGO_DB_ADD: "{{ .Values.dbName }}.{{ .Values.namespace }}.svc.{{ .Values.clusterdomain }}"