apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
  labels:
    run: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Values.appName }}
  template:
    metadata:
      labels:
        run: {{ .Values.appName }}
    spec:
      containers:
      - name: {{ .Values.appName }}
        image: jobri237/lab4-app:1
        ports:
        - containerPort: 80
        envFrom:
          - secretRef:
              name: {{ .Values.secret }}
        env:
          - name: MONGO_DB_ADD
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.configmap }}
                key: MONGO_DB_ADD
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name:  {{ .Values.dbName }}
  labels:
    run: {{ .Values.dbName }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.dbName }}
  template:
    metadata:
      labels:
        run: {{ .Values.dbName }}
    spec:
      containers:
      - name: {{ .Values.dbName }}
        image: mongo
        ports:
        - containerPort: 27017
        envFrom:
          - secretRef:
              name: {{ .Values.secret }}
        volumeMounts:
          - mountPath: /data/db
            name: mongodata
      volumes:
        - name: mongodata
          persistentVolumeClaim:
            claimName: {{ .Values.pvc }}