apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQ=
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  creationTimestamp: null
  name: {{ .Values.secret }}