apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.appName }}
spec:
  selector:
    run: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.dbName }}
spec:
  selector:
    run: {{ .Values.dbName }}
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017